# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Ananya Nandy
tagline:          'Portfolio in progress'
description:      'A place to get my work out into the world'
url:              http://ananyan.github.io
baseurl:          /

author:
  name:           'Ananya Nandy'
  url:            https://twitter.com/AnAnanyaNandy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ananyan.github.io 
  
plugins:          
    - jekyll-paginate
    - jekyll-gist
